### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by Princegupta101** [VaibhavCodeClub/learn#10]
We recommend that every repo has a code of conduct. If you don’t feel comfortable creating your own Code of Conduct from scratch we highly recommend using one of the templates provided by GitHub. If you do use a template, please read through the template and ensure that you can and will abide by the Code of Conduct.

Please follow these instructions on how to add a Code of Conduct.

Sample: https://github.com/Recode-Hive/Stackoverflow-Analysis/blob/main/CODE_OF_CONDUCT.md

**Comment by Saumya-28** [comment]
I would like to work on this issue as I have previously worked with quality documentations and written medium articles. Could you please assign me this issue?

**Comment by suhanipaliwal** [comment]
I would like to work on this issue. Please assign me this task.

**Comment by sapatevaibhav** [comment]
#70 as it was essential to add code of conduct I am creating it as well no update from assignee...
Sorry......

**Comment by suhanipaliwal** [comment]
@sapatevaibhav You can assign the issue to me. I will add the code of conduct as soon as possible.
