### ISSUE TITLE
URGENT | Bug in the app

### ISSUE THREAD

**Issue by xkaper001** [VaibhavCodeClub/learn#110]
## **Describe the bug**
While running the app the following errors are thrown : 
1. unable to locate image asset
> ═══ Exception caught by image resource service ═════
The following assertion was thrown resolving an image codec:
Unable to load asset: "assets/colours/colours-cover.png".
Exception: Asset not found
2. Unable to view Explore Screen
> A RenderViewport expected a child of type RenderSliver but received a child of type RenderSemanticsGestureHandler.

## **To Reproduce**
1. Run the app
2. Go to the explore tab in the app on the emulator
3. See error

## **Expected behavior**
A simple explore screen 

## **Screenshots**
![flutter_3](https://github.com/VaibhavCodeClub/learn/assets/71162979/a10222fa-a8c9-415e-8b0d-bf974e25fdb7)

**Comment by xkaper001** [comment]
Hey @sapatevaibhav could you assign me this issue

**Comment by sapatevaibhav** [comment]
are you on latest commit as it is working perfect here

**Comment by xkaper001** [comment]
> are you on latest commit as it is working perfect here

yes I rechecked it with `master` branch and latest commit `7ab08502` and It isn't working same issue persists
