### ISSUE TITLE
Improve app drawer and About page.

### ISSUE THREAD

**Issue by sapatevaibhav** [VaibhavCodeClub/learn#119]
Fix app drawer and About page behavior.
![image](https://github.com/VaibhavCodeClub/learn/assets/64630274/796588cd-3110-4853-874b-20e85cc912a1)
![image](https://github.com/VaibhavCodeClub/learn/assets/64630274/82b2ce6f-a15a-42a4-bca7-83fff49681da)
I mean make is more responsive

**Comment by Ashish-1020** [comment]
I am a gssoc contributor,Iwould like to work on this issue.Please assign me this issue.

**Comment by ReaganBlade** [comment]
Hello, I would like to work on this issue. Please assign me this

**Comment by zeba62** [comment]
I would like to work on this issue.
Can you please assign it to me.

**Comment by i-am-a-shish** [comment]
Hey!! i Would Really Like To Work On This 
Can You Assign The Task To Me

**Comment by VaibhavYT** [comment]
Hey!! I Would Really Like To Work On This.
Assign this to me I can easily debug this. I had done this before this many time.

**Comment by harsh6045** [comment]
I am also interested in making changes on UI. I am GSSOC's 24 Contributor I have an experience in flutter and I am interested in UI designing. @sapatevaibhav

**Comment by sapatevaibhav** [comment]
#131

**Comment by VaibhavYT** [comment]
Wow ok means I can contribute without assigned.

**Comment by harsh6045** [comment]
Thanks for assigning
