### ISSUE TITLE
Code improvement in home.dart

### ISSUE THREAD

**Issue by hiranj-kotak** [VaibhavCodeClub/learn#120]
i  have noticed that in home.dart there is a repetition of code in which makes it less readable

so @sapatevaibhav  please assign this task to me so that i can solve this

**Comment by khushikunte** [comment]
Hello .I am intrested in contributing for this task .Please assign me this under GSSOC'24

**Comment by hiranj-kotak** [comment]
> Hello .I am intrested in contributing for this task .Please assign me this under GSSOC'24

thanks for your intrest but i have already solved the issue and generated pr 

@sapatevaibhav  i request you to mark this issue as gssoc and accept my pr

**Comment by sapatevaibhav** [comment]
#121
