### ISSUE TITLE
Adding landing page for the application

### ISSUE THREAD

**Issue by a-m-a-nkumar** [VaibhavCodeClub/learn#124]
**Describe the Feature you'd like**
Developing a landing page for this application will offer visitors an engaging and informative introduction to this application.
We can have some quotes or animations or images that should reflect the core idea of the application.
**Additional context**
Currently, this application starts with the following page. Adding a captivating landing page would be even more beneficial.

![0](https://github.com/VaibhavCodeClub/learn/assets/99753046/01315cff-ceb9-4e69-8e76-b35106ddddb3)

**Comment by a-m-a-nkumar** [comment]
I am a GSSOC contributor and i would like to work on this issue.

**Comment by a-m-a-nkumar** [comment]
@sapatevaibhav I have completed the work on the landing page. If you want to update anything on the page, I am ready to do so.
![1](https://github.com/VaibhavCodeClub/learn/assets/99753046/bc9cdcdb-8cd4-400a-99f5-13766ca7755b)

**Comment by khushikunte** [comment]
Hello .I am intrested in contributing for this task .Please assign me this under GSSOC'24
