### ISSUE TITLE
UI overflow in drawer section

### ISSUE THREAD

**Issue by a-m-a-nkumar** [VaibhavCodeClub/learn#125]
**Describe the bug**
There is a UI overflow in drawer section

**To Reproduce**
1. Go to Home page
2. Click on Three Horizontal line to open drawer
3. Scroll down

**Expected behavior**
No overflow

**Screenshots**
![9](https://github.com/VaibhavCodeClub/learn/assets/99753046/7d24d30b-593c-4071-ba3b-9276be4cf9ad)

**Smartphone (please complete the following information):**
 - Device: POCO M2
 - OS: Android 11

**Comment by a-m-a-nkumar** [comment]
I am a GSSOC contributor and i would like to work on this issue

**Comment by sapatevaibhav** [comment]
#119
