### ISSUE TITLE
[Bug]: assets are not loading in Explore page

### ISSUE THREAD

**Issue by hiranj-kotak** [VaibhavCodeClub/learn#136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

To Reproduce 
1) run the app
2) go to Explore page 

### Expected behavior

the Explore page must display images on cover page

### Add ScreenShots

![Screenshot_1716450642](https://github.com/VaibhavCodeClub/learn/assets/95754714/8d57663e-ad15-46ce-8acb-b8670215744e)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by sapatevaibhav** [comment]
Make Quiz option like other options too so the issue can be considered as level1

**Comment by sapatevaibhav** [comment]
#121
