### ISSUE TITLE
[Feature Request]: Add Dependabot for flutter dependency Updates

### ISSUE THREAD

**Issue by samarsajad** [VaibhavCodeClub/learn#139]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I propose integrating Dependabot into our project to automate dependency updates. Dependabot will regularly check for updates, ensuring we stay current with the latest features and security patches. This will save time, enhance security, and maintain consistency in our development process.

### Use Case

Dependabot will regularly check for updates, ensuring we stay current with the latest features and security patches.

### Add ScreenShots

Na

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by samarsajad** [comment]
@sapatevaibhav Please assign me this issue 
Thank you

**Comment by samarsajad** [comment]
@sapatevaibhav Please add the level in the pull request #140
Thank you

**Comment by sapatevaibhav** [comment]
This was 1 point issue.
