### ISSUE TITLE
Make SVG from alphabets page theme adaptive

### ISSUE THREAD

**Issue by sapatevaibhav** [VaibhavCodeClub/learn#14]
**Is your feature request related to a problem? Please describe.**
Some of the SVGs are of black color.

**Describe the solution you'd like**
When we change theme to the dark those SVGs must turn to other color (preferabely white).

**Additional context**
![Screenshot_20240510-151044](https://github.com/VaibhavCodeClub/learn/assets/64630274/3b79056a-401a-4ee3-a99e-d7a22b4e75c5)

**Comment by Prathme07** [comment]
Please assign it to me

**Comment by kamalexe** [comment]
Please assign me to this task I can solve using Theme.of(context).brightness == Brightness.dark;

**Comment by Prathme07** [comment]
Actually if you use [Theme.of(context).brightness == Brightness.dark;] all the photos will either come in white and black irrespective to there orignal color. I arleady worked on that and came to conlusion to give the conatiner color or prepare two versions of each svg for light and dark mode

**Comment by Shubham-Zone** [comment]
i would like to contribute to this issue... kindly assign me i am GSSOC'24 contributor

**Comment by sapatevaibhav** [comment]
No need as background color is not black in dark mode too...
