### ISSUE TITLE
New Flutter Version

### ISSUE THREAD

**Issue by Maheen-Ilyas** [VaibhavCodeClub/learn#141]
There was an upgrade in the Flutter Version. MaterialStateProperty, MaterialStatePropertyAll and a few other are deprecated. Instead there is WidgetStateProperty. We can make the replacements.

I am a GSSoC'24 contributor.

**Comment by Maheen-Ilyas** [comment]
@sapatevaibhav WillPopScope is also deprecated. When I am replacing it with the new PopScope, I will have to make minor changes to the function called _onBackPressed. Can I make the change?
![Screenshot_1715853388](https://github.com/VaibhavCodeClub/learn/assets/111234735/f2ce5654-81a8-4c0b-8dba-d7b20f5efbd4)
The argument type 'Future<bool> Function()' can't be assigned to the parameter type 'void Function(bool)?'.

**Comment by sapatevaibhav** [comment]
#160
