### ISSUE TITLE
[Bug]:  UI issue in alphabets and animals section.

### ISSUE THREAD

**Issue by sapatevaibhav** [VaibhavCodeClub/learn#142]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

- UI is overflowing in alphabets section.
- Alphabets popup is not well structured for big screen.
- Fix animal popup for big screens.

### Expected behavior

1. Fix the overflow
2. The popup should be not big it must contain all prev, next and close buttons on single screen no need to scroll.
3. Make the animals popup big not so huge.

### Add ScreenShots

![image](https://github.com/VaibhavCodeClub/learn/assets/64630274/d6371909-2519-4138-a46e-158b2832f8ee)
![image](https://github.com/VaibhavCodeClub/learn/assets/64630274/8f11c6a1-5b1d-4562-8d7d-82cb7a0b9298)
![image](https://github.com/VaibhavCodeClub/learn/assets/64630274/cb4f4e80-4048-4894-a97e-f7e312ec779f)

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by prajapatihet** [comment]
Assign this to me

**Comment by HarshalMakwana986** [comment]
Can you please assign this to me @sapatevaibhav? 
I will solve the issue and do it as per the requirements.

**Comment by NamrataCSalvi** [comment]
I would like to work on this issue can you please assign it to me

**Comment by sapatevaibhav** [comment]
Sorry for the inconvenience the issue is fixed.
