### ISSUE TITLE
[Feature Request]: Add Drawing Board to Explore Section

### ISSUE THREAD

**Issue by AsmitaMishra24** [VaibhavCodeClub/learn#143]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to add a drawing board feature to the Explore section. This drawing board will provide a fun and interactive way for kids to practice what they've learned as well as explore their creativity through drawing and doodling.

### Use Case

How This Feature Would Enhance My Use of the Project

1. Increased Engagement: Kids will enjoy using the app more with the fun drawing tool.
2. Reinforced Learning: Provides a hands-on way for kids to practice alphabets and numbers.
3. Boosted Creativity: Encourages creative expression and fine motor skill development.
4. Versatile Learning: Can be used for multiple educational activities like drawing shapes or practicing writing.
5. Improved User Experience: Adds an enjoyable and educational feature, enhancing the overall app experience.

### Benefits

1. Learning: Kids can practice writing and drawing, which helps reinforce their learning.
2. Creativity: Encourages kids to be creative and improves their fine motor skills.
3. Fun: Makes the app more enjoyable with a fun activity.
4. Versatility: Can be used for various educational activities, like drawing the solar system or practicing writing.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by AsmitaMishra24** [comment]
Please assign me this issue for GSSoc'24.

**Comment by sapatevaibhav** [comment]
I'll give level label after first PR.

**Comment by AsmitaMishra24** [comment]
> I'll give level label after first PR.

ok

**Comment by sapatevaibhav** [comment]
#155
