### ISSUE TITLE
[Bug]: Flowers page redesign.

### ISSUE THREAD

**Issue by sapatevaibhav** [VaibhavCodeClub/learn#144]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The flowers page is lagging as well use common flowers not complex ones.

### Expected behavior

Make the colors page faster (you can make background of single of color) as well make the UI theme adaptive including the flowers option inside app drawer.

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by DS-1090** [comment]
I would like to work on it. Could you please assign it to me?

**Comment by Gaurav-Kushwaha-1225** [comment]
Hello, I would like to work on this issue. I have already worked on 3 issues of this project.
@sapatevaibhav

**Comment by SivaRamana-H-V** [comment]
I want to take on this task. Could you assign it to me?

**Comment by ChaitaleePatil** [comment]
I would like to work on this issue as part of my contribution to GGSOC. Could you please assign it to me?

**Comment by sapatevaibhav** [comment]
#165
