### ISSUE TITLE
Colours learning feature

### ISSUE THREAD

**Issue by DS-1090** [VaibhavCodeClub/learn#15]
I propose to integrate an interactive page within the Learn app to educate children about color names.
Features:
Colourful UI: Designed a visually appealing UI  
Voice Output: Implemented voice prompts that provide audio pronunciation of color names 
 
![image](https://github.com/VaibhavCodeClub/learn/assets/126580400/0098d3ea-30b8-4156-b912-2f01bd18b11c)
![image](https://github.com/VaibhavCodeClub/learn/assets/126580400/393ad993-3010-4840-828a-5418c3fdf338)

Please assign this feature request to me so that I can proceed with creating a pull request.

**Comment by sapatevaibhav** [comment]
Okay if you come with intuitive GUI I'll give it more priority for now it's Level 1

**Comment by DS-1090** [comment]
Okay, I'll focus on improving the GUI further, and then I'll proceed to generate a pull request.

**Comment by DS-1090** [comment]
I have made some changes: 
![image](https://github.com/VaibhavCodeClub/learn/assets/126580400/223b65ef-4e94-40c7-b886-fae5f6078085)
![image](https://github.com/VaibhavCodeClub/learn/assets/126580400/2e5639a8-01e0-457b-be36-8982e08f83c5)
![image](https://github.com/VaibhavCodeClub/learn/assets/126580400/6d2e2966-2bdc-40aa-a7ba-e559f2c7c4e2)
Let me know if there are any further improvements.

**Comment by sapatevaibhav** [comment]
Great! Just keep in mind that we have to use svg files such that application size doesn't increase a lot.😊

**Comment by DS-1090** [comment]
Ohh, didn't know that, I converted those files back to SVG. and can you update the level?

**Comment by sapatevaibhav** [comment]
Done at #19
