### ISSUE TITLE
Functions used are repeated in almost all modules

### ISSUE THREAD

**Issue by Maheen-Ilyas** [VaibhavCodeClub/learn#161]
Functions like readName, navigateToPrevious and navigateToNext are repeated in almost all the modules. We can write common functions and pass the length of the list as argument. This way we will be able to avoid rewriting the function.

**Comment by Maheen-Ilyas** [comment]
I am a gssoc'24 contributor. Please consider this

**Comment by Shubham-Zone** [comment]
@VaibhavCodeClub please assign this to me i am GSSOC'24 contributor and have 2+ years of experience in flutter
