### ISSUE TITLE
[Feature Request]: Dark Mode feature.

### ISSUE THREAD

**Issue by Nikitakandwal** [VaibhavCodeClub/learn#162]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The dark mode feature for the "Learn" app makes the screen darker to help kids read comfortably in the dark or dim light. It's like turning off the lights in the app.

### Use Case

1. Reading in the Dark: Kids can use dark mode when it's dark to avoid straining their eyes. It's like using a nightlight for reading.

2. Easy to See: Dark mode makes the words easier to read, especially in low light. It's like using a flashlight in the dark.

3. Choose What's Best: With dark mode, kids can pick the theme they like best. It's like picking the color of their room.

### Benefits

1. Less Eye Strain: Dark mode helps kids read without hurting their eyes, making learning more comfortable.

2.  Simple and Cool: Dark mode makes the app look trendy and modern, making kids want to use it more.

3. Fits Your Style: Kids can choose the theme they like, making the app feel more like their own.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by sapatevaibhav** [comment]
Some screenshots of the issue please...

**Comment by Nikitakandwal** [comment]
Sure! I tried to implement the feature as early as possible. 
<img src="https://github.com/VaibhavCodeClub/learn/assets/98966392/c7fad5fd-0232-4363-a83a-055f6382c717" width="300">
<img src="https://github.com/VaibhavCodeClub/learn/assets/98966392/09d19936-88e7-4c87-ba2d-5a4c599b0137" width="300">

**Comment by Nikitakandwal** [comment]
I have implemented the functionality on the button that was already present in the home page to avoid any confusion.

**Comment by sapatevaibhav** [comment]
send PR

**Comment by Nikitakandwal** [comment]
> send PR

Can you please assign this issue first and put labels to this issue under gssoc

**Comment by Nikitakandwal** [comment]
> send PR

I've just sent a PR for the dark mode feature. Kindly review it!
