### ISSUE TITLE
Making solar System Screen

### ISSUE THREAD

**Issue by Prathme07** [VaibhavCodeClub/learn#17]
I would like to make Solar System screen so would you please again it to me

**Comment by Peehu1308** [comment]
can you please assign it me

**Comment by Prathme07** [comment]
@sapatevaibhav I think this issue should be of level 3 I guess. Correct me if I am wrong

**Comment by hiranj-kotak** [comment]
@sapatevaibhav  I would like to work on this issue with @Prathme07. can you please assign me this issue

**Comment by Prathme07** [comment]
@hiranj-kotak  thank you for showing your interest in this issue but I have already resolve that issue and I was facing diificty in navitaing back to home screen but I got it where I was doing wrong. Thanks once again.

**Comment by sapatevaibhav** [comment]
> @sapatevaibhav I think this issue should be of level 3 I guess. Correct me if I am wrong

No bro there are several issues which require high skills and efforts too..

**Comment by Prathme07** [comment]
@sapatevaibhav thank you for the information. And please assign the issues that you think I will be capable to ressolve

**Comment by sapatevaibhav** [comment]
#41
