### ISSUE TITLE
[Bug]: All the Flowers are not listed in the routs

### ISSUE THREAD

**Issue by vijaymehrotra** [VaibhavCodeClub/learn#175]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

in the path -> " learn/lib/utils/assets_path.dart " all the flowers are not listed due to which the app is not working properly..

### Expected behavior

All the flowers should be listed in the flowers class...
" Carnation , daffodil and poppy ", are not listed in the flowers class...

### Add ScreenShots

![image](https://github.com/VaibhavCodeClub/learn/assets/115913159/91e97d1c-e3c3-410c-8996-26c3b9da578d)

Due to this app is not running

### On which device are you experiencing this bug?

Android

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by sapatevaibhav** [comment]
SOmeone alredy raised PR #176
