### ISSUE TITLE
[Feature Request]: Make explore page better

### ISSUE THREAD

**Issue by sapatevaibhav** [VaibhavCodeClub/learn#193]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Make top option look alike all others as  well add all the modules which are currently available in the app to the explore page.

### Use Case

Makes explore page good.

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I have starred the repository

**Comment by VITianLalit** [comment]
@sapatevaibhav , pls assign me this issue, I want to work on it.

**Comment by sapatevaibhav** [comment]
GSOC or VSOC?

**Comment by VITianLalit** [comment]
@sapatevaibhav , GSOC.... I'll do as soon as possible.

**Comment by VITianLalit** [comment]
@sapatevaibhav , Pls, Review and Merge my Pull request......for this issue...
