### ISSUE TITLE
[Feature Request]: Implement Favourites page

### ISSUE THREAD

**Issue by sapatevaibhav** [VaibhavCodeClub/learn#194]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Add the favorites (heart) option in the right corner of each list item in the explore page and when the item is favorite it must be visible in favorites page as well change the look of heart to red as denoting this is favorite item else keep it gray.

### Use Case

There will be no need to go through entire explore page

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [ ] I'm a VSoC'24 contributor
- [X] I have starred the repository

**Comment by VITianLalit** [comment]
@sapatevaibhav , pls Assign me this issue.

**Comment by VITianLalit** [comment]
@sapatevaibhav , now, Pls Assign me this task too.....

**Comment by VITianLalit** [comment]
@sapatevaibhav , I have made pull request, pls review and merge it.....
