### ISSUE TITLE
Number Learning Feature

### ISSUE THREAD

**Issue by vamzx** [VaibhavCodeClub/learn#20]
A feature to teach numbers just as other topics like A-Z, animals, shapes. etc.

**Comment by vamzx** [comment]
I am a GSSoC'24 contributor, so please do consider this feature and assign it to me.

**Comment by vamzx** [comment]
@sapatevaibhav I am unable to clone the repo due to the con.png bug that is mentioned in another issue

**Comment by hariram62** [comment]
@vamzx
git clone [url of the repo which u have forked]
// run this command in the root directory after cloning.
git restore --source=HEAD :/
// and then. 
git add .
git commit -m "[commit message]"
git push origin [branch_name]

**Comment by LEARNER-dakshesh** [comment]
Hello Vaibhav ! I wanted to work on this issue. Can you please assign me ?

**Comment by vamzx** [comment]
@sapatevaibhav I am done with most functionalities but I am unable to find SVGs for the images online for free. Are there any resources you know where I can find them?

**Comment by sapatevaibhav** [comment]
https://www.pngtosvg.com/
https://www.flaticon.com/
https://www.svgrepo.com/

**Comment by LEARNER-dakshesh** [comment]
Hey @sapatevaibhav can you please asssign me this issue . I can work on this

**Comment by vamzx** [comment]
@sapatevaibhav there seem to be a lot of errors in flutter tts related code, could you please check that?

**Comment by NamrataCSalvi** [comment]
I would like to work on this issue.Can you assign it to me
