### ISSUE TITLE
Add AppConstants

### ISSUE THREAD

**Issue by sapatevaibhav** [VaibhavCodeClub/learn#23]
Add the `AppConstants.dart` file and move all the strings used in the Dart files to that file. Define the strings in `AppConstants.dart` as follows:

```dart
class AppConstants {
  static const String nose = "Nose";
  static const String noseDescription = "This is nose description";
}
```

Then, access them from other files like this:

```dart
Text(AppConstants.noseDescription)
```

It is important for clean, organized, and easily maintainable codebase,

**Comment by Gaurav-Kushwaha-1225** [comment]
Hi @sapatevaibhav, I am a contributor under GSSoC'24. Can you assign this issue to me??

**Comment by VedaVarxha** [comment]
@sapatevaibhav I would like to work on this issue under GSSOC'24. Please assign it to me.

**Comment by hariram62** [comment]
@sapatevaibhav I would like to contribute on this issue.... Can you please assign it to me? i have some experience on this... you can look on to this repo [](https://github.com/hariram62/MentHer-DevsHouse-24)..

**Comment by mayankgongal5** [comment]
Hey @sapatevaibhav can you please assign this to me ? its my first time in gssoc and I am intermediate in fluter

**Comment by kamalexe** [comment]
I can address the UI issue in Alphabet section #28. Please assign it to me. I am participating in GSSoC'24.

**Comment by hiranj-kotak** [comment]
Hey @sapatevaibhav  can you assign this issue to me ? I have 1 year experience  in flutter

**Comment by aryanmehra0** [comment]
@sapatevaibhav hii I want to be contributer to this particular task plz assign this to me

**Comment by Gaurav-Kushwaha-1225** [comment]
Should I move the common or constant functions to the AppConstants file too??

**Comment by sapatevaibhav** [comment]
> Should I move the common or constant functions to the AppConstants file too?? @sapatevaibhav 

Just make a separate file for functions..
