### ISSUE TITLE
There is a issue while cloning the project, due to "con.png" available in "assets/images/ "

### ISSUE THREAD

**Issue by Rajkumarbhakta** [VaibhavCodeClub/learn#27]
![Screenshot (27)](https://github.com/VaibhavCodeClub/learn/assets/85289204/b5c8c107-556a-4cc7-9a5b-0b8f09c80ed1)

**Comment by Rajkumarbhakta** [comment]
Hello I'm from GSSoC'2024. I can fix this issue please assign to me.

**Comment by kamalexe** [comment]
I can address the UI issue in Alphabet section #28. Please assign it to me. I am participating in GSSoC'24.

**Comment by sapatevaibhav** [comment]
#31 done
