### ISSUE TITLE
UI issue in Alphabet section

### ISSUE THREAD

**Issue by Rajkumarbhakta** [VaibhavCodeClub/learn#28]
1 . Every single item overflowed.

<img alt="Home" src="https://github.com/VaibhavCodeClub/learn/assets/85289204/9ff7a9e1-dbf9-42be-96e8-199f957e7d3f" width="250"/>

2 . The bottom sheet card is not properly rounded corner.

<img alt="Home" src="https://github.com/VaibhavCodeClub/learn/assets/85289204/35d26e69-d675-45a1-a4fb-9ad7d37fe4c6" width="250"/>

3. Suggestion : It would be better if the popup is a dialog rather than a bottom sheet.

**Comment by pavants777** [comment]
I can resolve this issue assign for me ..

**Comment by kamalexe** [comment]
I can address the UI issue in Alphabet section #28. Please assign it to me. I am participating in GSSoC'24.

**Comment by Pra-kas** [comment]
I am from GSSOC'24. I can able to fix this issue please assign me.

**Comment by Hetpra9653** [comment]
@Rajkumarbhakta i got issue it may be happened due to you are not given expanded to text and for bottom sheet you have to give borderradius i think you should use cliprrect for that asssign this issue to me i will solve it

**Comment by sapatevaibhav** [comment]
#31 done.

**Comment by kamalexe** [comment]
![WhatsApp Image 2024-05-11 at 23 39 39_1b91143c](https://github.com/VaibhavCodeClub/learn/assets/83895579/49da6b12-a624-4810-8277-8e8a91112be8)
It 
![WhatsApp Image 2024-05-11 at 23 39 40_b679741b](https://github.com/VaibhavCodeClub/learn/assets/83895579/3e4b06af-4fc1-48e1-b8d0-90182d929880)
look All ready fixed, Can you explain what i have to fix??

**Comment by kamalexe** [comment]
Modal BottomSheet to Dialog as you Suggestion, Is it ok ! I'm absolute beginner
![WhatsApp Image 2024-05-12 at 00 20 22_cc8291c2](https://github.com/VaibhavCodeClub/learn/assets/83895579/48c4b5b5-de7a-4ffe-9d8b-cf13edfa3666)
