### ISSUE TITLE
Implement Google Login Feature

### ISSUE THREAD

**Issue by vamzx** [VaibhavCodeClub/learn#29]
Instead of entering all credentials every time, we can add the feature of allowing users to log in through their google account.

I am a contributor of GSSoC '24 and I am confident I can add this feature in a short span of time, so please do assign this work to me

**Comment by sapatevaibhav** [comment]
I currently don't want to include a login feature, as it would make the application more complex and would involve additional tracking by Google. Hope you will understand...
