### ISSUE TITLE
Add a section for common flowers.

### ISSUE THREAD

**Issue by Rajkumarbhakta** [VaibhavCodeClub/learn#37]
It would be grate if there is also a section for common flowers.

**Comment by Rajkumarbhakta** [comment]
I want to work in this. Please assign me.

**Comment by LEARNER-dakshesh** [comment]
Hello Vaibhav ! I wanted to work on this issue. Can you please assign me ?

**Comment by Shubham-Zone** [comment]
i would like to contribute to this issue... kindly assign me i am GSSOC'24 contributor

**Comment by khush1yaaar** [comment]
Hey, Khushi Soni this side, I'm a GSSoC contributor and would love to handle this issue

**Comment by Chekka-Mounika** [comment]
I am GSSoC'24 contributor. Please assign me this issue.
