### ISSUE TITLE
Ui issue in body parts section.

### ISSUE THREAD

**Issue by Rajkumarbhakta** [VaibhavCodeClub/learn#38]
The body parts images are overflowed.
<img src='https://github.com/VaibhavCodeClub/learn/assets/85289204/d545f6f4-0ed4-4d24-b426-77b8180341e1' width='250'/>

**Comment by Rajkumarbhakta** [comment]
I want to work on this issue please assign me.

**Comment by sapatevaibhav** [comment]
Fix it using device height and width as on the big screen it goes to the corner.

```dart
 width: MediaQuery.of(context).size.width * 0.3,
```

![Screenshot_20240511-215559.png](https://github.com/VaibhavCodeClub/learn/assets/64630274/79cbfc1a-d77e-48f1-8ac7-3e9ebc05324a)

**Comment by LEARNER-dakshesh** [comment]
Hello Vaibhav i wanted to work on this issue. Can you please assign me ?

**Comment by Partha02Bh** [comment]
Hello Sir @sapatevaibhav I want to work on this issue..Please assign me

**Comment by sapatevaibhav** [comment]
#43
