### ISSUE TITLE
Enhance User interface (UI)

### ISSUE THREAD

**Issue by Prathme07** [VaibhavCodeClub/learn#4]
Hi,
I would like to enhance the user interface by adding some styling of buttons, drawer, improving appbar and etc. I would like to correct that thing that I have attached. I am working on that so please will you please allocate that to me.
![learn](https://github.com/VaibhavCodeClub/learn/assets/126415903/a51c150c-1ff9-490f-acee-50a8e2823676)

**Comment by bhavanishanker-png** [comment]
Please allocate this task to me. I'm capable of tackling it as I possess all the requisite skills to address the matter at hand.

**Comment by sabbu143s** [comment]
please allocate me i will improve the ui of the app

**Comment by Prathme07** [comment]
![corrected_light](https://github.com/VaibhavCodeClub/learn/assets/126415903/5e6ec06b-9c49-4354-a289-8e36a7969b72)
![corrected_dark](https://github.com/VaibhavCodeClub/learn/assets/126415903/c273c159-c083-42c6-aa04-5ed88519e861)


I had corrected the issue if you will allow me I will merge it or send a pull request

**Comment by sapatevaibhav** [comment]
Yes, you can send the PR.

**Comment by hharshapareekk** [comment]
Hey, 
Few of the issues that i noticed  and that could be implemented for better user interface:
 - Generic plain background ui -> could add a shade and even app bars and bottom nav bars for enhancement
 - The container not having uniform border radius
 - change the container having black borders to a container with shadows.
 
 
 I have implemented amazing user interfaces for my flutter app that you can check on my github profile.Would be happy to work on this issue. Do consider me for this issue.
Regards.

**Comment by Prathme07** [comment]
@hharshapareekk Actucally I am a contributor too In GSSoC and I had opened that issue so that I can work on that and curently I am working on the UI part as mentioned above. Hope you understand.

**Comment by sapatevaibhav** [comment]
@hharshapareekk If you're planning on making more UI improvements beyond #12, you're totally welcome to do so.

**Comment by Prathme07** [comment]
@sapatevaibhav will you please mention the level of the issue

**Comment by LEARNER-dakshesh** [comment]
Hello Vaibhav ! I wanted to work on this issue. Can you please assign me ?

**Comment by sapatevaibhav** [comment]
#42
