### ISSUE TITLE
Taking confirmation from user if he want to leave the app or not

### ISSUE THREAD

**Issue by Prathme07** [VaibhavCodeClub/learn#44]
We can add an feature in which if user press the back button to leave the app a pop screen will come and ask the user Please confirm
do you want to leave the app.

As we are creating an app for childern there might be possiblity that by mistake the app is closed so if we add this feature it would be great

**Comment by sapatevaibhav** [comment]
Instead confirmation add the toast saying *press back again* to exit.

**Comment by Prathme07** [comment]
okay so will you please assign it to me

**Comment by Prathme07** [comment]
@sapatevaibhav I have created a pull request of this issue. Please let me know if any change is needed.

Thank you for your kind attention

**Comment by Shubham-Zone** [comment]
i would like to contribute to this issue... kindly assign me i am GSSOC'24 contributor

**Comment by sapatevaibhav** [comment]
#46
