### ISSUE TITLE
add a section for comman fruits names

### ISSUE THREAD

**Issue by dev04sa** [VaibhavCodeClub/learn#49]
**Is your feature request related to a problem? Please describe.**
i want to add a new section for command fruits names

**Describe the solution you'd like**
similar to birds name . i will add cards for fruits.

**Comment by dev04sa** [comment]
@sapatevaibhav kindly assign this issue to me.

**Comment by Shubham-Zone** [comment]
i would like to contribute to this issue... kindly assign me i am GSSOC'24 contributor

**Comment by sapatevaibhav** [comment]
Go to #21.
