### ISSUE TITLE
Add Interactive Quizzes

### ISSUE THREAD

**Issue by DivyanshiSingh00** [VaibhavCodeClub/learn#52]
This way users can participate in interactive quizzes after completing their learning. This could be a great way to encourage them.
I would like to contribute to this issue...please assign me

**Comment by Prashant-2024** [comment]
I would like to help in this quiz Module, i have developed quiz application and have the right amount of knowledge to work on this.

Please assign this issue to me under GSSOC'24

**Comment by sapatevaibhav** [comment]
Quizzes section must be visible only in explore section....

**Comment by DivyanshiSingh00** [comment]
> Quizzes section must be visible only in explore section....

okay!!!! working on it still.

**Comment by DivyanshiSingh00** [comment]
> Quizzes section must be visible only in explore section....

okay!!!! working on it still.

**Comment by Prashant-2024** [comment]
Acknowledge
