### ISSUE TITLE
Birds Section UI Issue

### ISSUE THREAD

**Issue by Maheen-Ilyas** [VaibhavCodeClub/learn#53]
The Play Sound button and the arrows on either side of it are not aligned well. Please allow me to correct it.

![Screenshot_1715531676](https://github.com/VaibhavCodeClub/learn/assets/111234735/51a4e8b1-c1d4-4452-a071-71c8d233c5ad)

**Comment by Maheen-Ilyas** [comment]
I am a gssoc'24 contributor. Please assign this issue to me.

**Comment by khush1yaaar** [comment]
Hey, Khushi Soni this side, I'm a GSSoC contributor and would love to handle this issue

**Comment by sapatevaibhav** [comment]
#79
