### ISSUE TITLE
Occupation module

### ISSUE THREAD

**Issue by Maheen-Ilyas** [VaibhavCodeClub/learn#55]
**Is your feature request related to a problem? Please describe.**
A module can be added which teaches the children about the different occupations like doctor, policeman etc and where they work.

**Describe the solution you'd like**
I want to implement a module that displays the different occupations and their descriptions

**Describe alternatives you've considered**

**Additional context**

**Comment by Maheen-Ilyas** [comment]
I am a gssoc'24 contributor. Please consider this enhancement

**Comment by khush1yaaar** [comment]
Hey, Khushi Soni this side, I'm a GSSoC contributor and would love to handle this issue

**Comment by sapatevaibhav** [comment]
#96 

@khush1yaaar  please wait some time due to exams I am not properly focusing on the project.....

**Comment by khush1yaaar** [comment]
@sapatevaibhav Yeah that's fine 👍🏻
