### ISSUE TITLE
Changes to home page.

### ISSUE THREAD

**Issue by sapatevaibhav** [VaibhavCodeClub/learn#56]
Derive all the available options from drawer to home page (keep there too as well not about one) 
- If possible use more attractive GUI (images too).

**Comment by sapatevaibhav** [comment]
@kamalexe

**Comment by Prathme07** [comment]
@sapatevaibhav will you please assign this issue to me.

**Comment by Prashant-2024** [comment]
I would like to work on this issue under GSSOC'24.
Please assign it to me.

I have developed quite good apps in Flutter
