### ISSUE TITLE
Sperating home screen code from main.dart code

### ISSUE THREAD

**Issue by Prathme07** [VaibhavCodeClub/learn#60]
Hello @sapatevaibhav I think it would be great if we remove home screen code from main.dart as it will increase the code readablity and it will be great for other's to understand the code.

**Comment by sapatevaibhav** [comment]
@xkaper001 please mention here that you are working on this task such that reviewers from GSSoC can ensure that this task is assigned to you...

**Comment by xkaper001** [comment]
Hi Contributors and Mentors, I have already worked upon this issue and made a PR regarding this in #63

**Comment by Prathme07** [comment]
@sapatevaibhav actually I am new to open source contribution and I want to know that can we that anybody issue and solve that even that issue has already assigned to other person?

**Comment by sapatevaibhav** [comment]
> @sapatevaibhav actually I am new to open source contribution and I want to know that can we that anybody issue and solve that even that issue has already assigned to other person? 

No, if a contributor who has assigned for that issue doesn't provide any update on the task then it will be assigned to the next contributor.

**Comment by Prathme07** [comment]
@xkaper001 if someone is raising the issue that clearly means that that person whats to work on that. Hope you understand that and its okay I just want to know is that allowed or not.

**Comment by xkaper001** [comment]
> @xkaper001 if someone is raising the issue that clearly means that person wants to work on that. Hope you understand that and its okay I just want to know is that allowed or not.

Where did you learn that my friend? 😇 
[Clear your misunderstanding here.](https://chat.openai.com/share/36729a82-730d-4a29-a488-b879f8122be9)

**Comment by Prathme07** [comment]
@xkaper001 ok bro I didn't knew that
