### ISSUE TITLE
Implement the Explore Page

### ISSUE THREAD

**Issue by xkaper001** [VaibhavCodeClub/learn#62]
https://github.com/xkaper001/learn/blob/6e3e3a9d4dfae54b32d0e1dc1740402044a00538/lib/pages/explore.dart#L5

Implement the Explore page by adding all the avalable modules for the user here.

**Comment by xkaper001** [comment]
Hey @sapatevaibhav, Please assingn me this issue.

**Comment by iamkrishnagupta** [comment]
Hey, I would like to work on this issue. Please assign me this issue.
Thank you.

**Comment by khush1yaaar** [comment]
Hey, Khushi Soni this side, I'm a GSSoC contributor and would love to handle this issue
