### ISSUE TITLE
Updating App Logo

### ISSUE THREAD

**Issue by AsmitaMishra24** [VaibhavCodeClub/learn#64]
**Is your feature request related to a problem? Please describe.**
The current logo used in the Flutter application lacks appeal and may not effectively represent the brand or app's identity. A better logo could enhance the overall aesthetic and branding, potentially leading to increased user engagement and recognition.

**Describe the solution you'd like**
I propose creating a new logo that is more visually appealing, memorable, and representative of the app's purpose or theme. The logo should be designed to be compatible with both Android and iOS platforms, ensuring consistency across different devices. It should also be scalable to different sizes without losing clarity or quality.

**Record**

✅ I agree to follow this project's Code of Conduct
✅ I'm a GSSOC'24 contributor
✅ I want to work on this issue

**Comment by AsmitaMishra24** [comment]
Please assign me this issue.

**Comment by Prashant-2024** [comment]
I would like to address this issue under GSSOC'24.
Please assign it to me
