### ISSUE TITLE
Add another module of Seasons

### ISSUE THREAD

**Issue by AsmitaMishra24** [VaibhavCodeClub/learn#65]
**Is your feature request related to a problem? Please describe.**
The app currently lacks a dedicated module for exploring the four seasons: Spring, Summer, Autumn, and Winter.

**Describe the solution you'd like**
Add a new module titled "Seasons Serenade" to the app, providing educational content about each season.

**Describe alternatives you've considered**
Integrating seasonal content into existing modules, but a dedicated module would offer a more comprehensive experience.

**Comment by AsmitaMishra24** [comment]
Please assign me this issue.

**Comment by AsmitaMishra24** [comment]
I am a GSSoC'24 contributor, so please do consider this feature

**Comment by Prashant-2024** [comment]
I'm really sorry for not asking assigning request beforehand, I got confused between multiple issues and directly raised a PR

**Comment by sapatevaibhav** [comment]
Sorry from my side too because of exams as well I was not sure to add seasons as kids have knowledge of those things.

**Comment by AsmitaMishra24** [comment]
Could you kindly confirm if the issue I have created is open for anyone to work on?  I'm new to open source and I don't have much knowledge

**Comment by AsmitaMishra24** [comment]
I decided to work on this project because I want to learn Flutter.....Please confirm if I have created an issue, so anyone can get it assigned.

**Comment by sapatevaibhav** [comment]
@Prashant-2024  already submitted the PR I request him not to do so onward.. I will assign this to him.

**Comment by sapatevaibhav** [comment]
@AsmitaMishra24  You can work on another issue or raise another one.

**Comment by AsmitaMishra24** [comment]
Ok

**Comment by Prashant-2024** [comment]
I'm terribly sorry for causing this inconvenience to @AsmitaMishra24

**Comment by Prashant-2024** [comment]
This PR is merged, @sapatevaibhav You can close this issue after reviewing the PR
