### ISSUE TITLE
Learn.md

### ISSUE THREAD

**Issue by Princegupta101** [VaibhavCodeClub/learn#8]
Learn repos should have a LEARN.md file to teach student how to build your project step by step. You can explain how to build your project with text, code snippets, images, or even short (5 minute) long video lessons. As the maintainer of a Learn repo, the LEARN.md file requires you to think critically about how to explain the building of your project and how to also make it engaging. We don't expect you to be an expert teacher, but we would like you to reflect on how difficult it was to get to your level of knowledge, and then provide friendly guidance to help other students to learn.

Reference: https://github.com/Recode-Hive/Stackoverflow-Analysis/blob/main/Learn.md

**Comment by sapatevaibhav** [comment]
This will take some time as my end-of-semester exams have started. 😔

**Comment by hariram62** [comment]
i would like to contribute to this issue... can u pls assign me?

**Comment by hariram4862** [comment]
@sapatevaibhav Hi. I have sem exams this week. Probably, I will continue contributing from 21st may. So, I kindly request you to hold me as assignee.

Thank you.

**Comment by sapatevaibhav** [comment]
Yes same here wishes for the sem exam... After that we all will work hard here...

**Comment by crazyshrut** [comment]
Hey, I am a gssoc contributor, I want to contribute to this issue can you please assign this to me?

**Comment by crazyshrut** [comment]
I attempted to solve this issue, 
Could you please review?
https://github.com/VaibhavCodeClub/learn/pull/209
