### ISSUE TITLE
Add Game-Based Test After Learning 

### ISSUE THREAD

**Issue by ykhan2476** [VaibhavCodeClub/learn#88]
To enhance the learning experience and reinforce knowledge retention, it would be beneficial to integrate a game-based test at the end of each learning module. This interactive approach can make the learning fast.

** the solution can be **

After learning  kid can test knowledge by playing a  mcq - based game   by chosing the correct photo of the mentioned name . and result is generated showing the score . this will increase learning.

**Comment by ykhan2476** [comment]
Please assign me this issue . 

I am a GSSoC'24 contributor, so please do consider this feature.

**Comment by NamrataCSalvi** [comment]
I would like to work on this issue. Can you please assign it to me.

**Comment by sapatevaibhav** [comment]
@ykhan2476  update?
