### ISSUE TITLE
Move dimentions to seperate file.

### ISSUE THREAD

**Issue by sapatevaibhav** [VaibhavCodeClub/learn#91]
To make UI more powerful move all the UI related dimensions to the separate file.

like if you want to give the height of 20 to `SizedBox` then we should implement that dimension in that new file named `dimensions.dart` as
```dart
SizedBoxHeightSmall  = 10;
SizedBoxHeightMedium  = 20;
SizedBoxHeightHuge  = 30;
```
and give that dimension in our file by importing the dimensions file like.
```dart
const SizedBox(
  height = SizedBoxHeightMedium,
);
``` 
and so on for mediaQuery for making device independent screens too...

**Comment by Gaurav-Kushwaha-1225** [comment]
@sapatevaibhav Can you assign this issue to me??

**Comment by harsh6045** [comment]
I can improve the code quality as well as move the dimensions. I am also interested in making changes on UI. I am a GSSOC's 24 Contributor I have an experience in flutter. @sapatevaibhav
