### ISSUE TITLE
Adding list of contributors image under readme

### ISSUE THREAD

**Issue by Arpcoder** [VaibhavCodeClub/learn#92]
**Describe the solution you'd like**
List of contributors image under readme

**Additional context**
![Screenshot 2024-05-18 124533](https://github.com/VaibhavCodeClub/learn/assets/100352419/8ca798d3-c2f4-4d13-b9e5-7c03270fbc5b)

**Comment by Shruti78** [comment]
add me I will do that for you.

**Comment by Arpcoder** [comment]
> add me I will do that for you.

No, thank you

**Comment by sapatevaibhav** [comment]
Instead adding in readme.md add new markdown file contributors.md

**Comment by Arpcoder** [comment]
> Instead adding in readme.md add new markdown file contributors.md

Sure

**Comment by Arpcoder** [comment]
@sapatevaibhav .Please change the syntax of 'Level1' to 'level1' as per the GSSoC
