### ISSUE TITLE
Move all the models to a separate folder

### ISSUE THREAD

**Issue by Maheen-Ilyas** [VaibhavCodeClub/learn#97]
As the number of modules in the application are increasing, the model classes for the each module will also increase. We can create a models folder and move all the models into that folder. This will make the codebase clean and in the future, the contributors can make changes if needed with ease.

I am GSSoC'24 contributor. Please consider this.

**Comment by xkaper001** [comment]
Hi Contributors and Mentors, I have already worked upon this issue and made a PR regarding this in #83 (merged already)
Furthur
- All the models have been moved to a `module` folder  making the codebase cleaner.

Hey @sapatevaibhav could you assign me and close this issue as completed.

**Comment by Maheen-Ilyas** [comment]
This issue is regarding these classes.
class Bird {
  final String name;
  final String svgAsset;
  final String soundAsset;
  final Color backgroundColor;

  Bird({
    required this.name,
    required this.svgAsset,
    required this.soundAsset,
    required this.backgroundColor,
  });
}

**Comment by xkaper001** [comment]
> This issue is regarding these classes. class Bird { final String name; final String svgAsset; final String soundAsset; final Color backgroundColor;
> 
> Bird({ required this.name, required this.svgAsset, required this.soundAsset, required this.backgroundColor, }); }

could you elaborate

**Comment by Maheen-Ilyas** [comment]
> > This issue is regarding these classes. class Bird { final String name; final String svgAsset; final String soundAsset; final Color backgroundColor;
> > Bird({ required this.name, required this.svgAsset, required this.soundAsset, required this.backgroundColor, }); }
> 
> could you elaborate

Each module has these classes. We can have a folder called models and move them to a separate file in the folder.

**Comment by xkaper001** [comment]
> Each module has these classes. We can have a folder called models and move them to a separate file in the folder.

check with the latest commit on master branch. I made a `model` folder with a `module` class in it. and all the modules are placed in `pages/modules` (except the new ones being made by other contributors)

**Comment by sapatevaibhav** [comment]
#112
